// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzcpfanhxzygeqfjdetk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6Y3BmYW5oeHp5Z2VxZmpkZXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NjUwMDUsImV4cCI6MjA1NzA0MTAwNX0.hG2jYuzRikspDDLhe_y-eoOkjvXf4EOz_8kGsVkwGNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);